ZILLOW_RAPIDAPI_KEY = "eb33dcba92msh06b4f01c58f999ap1d105cjsn733b79d1d34c"
RENTCAST_API_KEY = "93d7c4c28dbc4c85945faad6b50c6be9"
RENTOMETER_API_KEY = "mmNaJff2pIsP84bUsvekXQ"
SUPABASE_URL = "https://spsfxgznsykeyrzbosmk.supabase.co"
SUPABASE_API = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwc2Z4Z3puc3lrZXlyemJvc21rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMDY0NjIsImV4cCI6MjA2NzY4MjQ2Mn0.swVujUd8VgJCmnB-R5OhLrkxr5Kr3aBD1v1lpWf6gXA"